### ISSUE TITLE
Rough roadmap/ideas

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-integration-elasticsearch#1]
Rough sketch of what we can do to improve Elasticsearch integration in Logstash.

### Unification:

One plugin, fewer dependencies, more shared code.

- [ ] [Patch doc generation to work correctly with a unified repository](https://github.com/elastic/docs-tools/issues/11)
- [ ] Ensure Jarvis will be able to publish the plugin 
- [ ] Update input/filter/output repos to all point toward this one in README
  - We will maintain the original repo's code completely because that is needed for releasing old branches.
- [ ] Move all elasticsearch plugins to a single repository (filter, output, input)
- [ ] Have all elasticsearch plugins use the same underlying library for accessing Elasticsearch (today they are all different)
- [ ] Rewrite elasticsearch plugins to use the Elasticsearch Java client.

### Outputs: Split by use case

The ES output has nearly 50 settings and has too many different uses. It's confusing.

Idea: Focus the 'elasticsearch output' *just* indexing documents (log use case). Create new plugins for other use cases.

1) Common-case indexing (create documents only, the primary use case)
2) Updates and aggregation use case (scripted updates, aggregations, rollups, etc)
3) Database sync scenario (copying records/transactions from a primary data store to Elasticsearch)

### Outputs: Improve memory usage when serializing

Currently we serialize a bulk and write the whole bulk. We could serialize one-at-a-time instead and use less memory for a shorter period of time. Better, with Elasticsearch Java client, we could probably even serialize directly to the socket.

### Input

1) Make the input support scheduling (cron, interval, etc)
2) Make the input support more than just scrolls?

**Comment by original-brownbear** [comment]
@jordansissel 

> Currently we serialize a bulk and write the whole bulk. We could serialize one-at-a-time instead and use less memory for a shorter period of time. Better, with Elasticsearch Java client, we could probably even serialize directly to the socket.

+1

I guess an easy way to do this and also take the first step for https://github.com/elastic/logstash/issues/7039 would be to just to add 

```java
public void writeAsJson(final OutputStream outputStream) throws IOException {
        JSON_MAPPER.writeValue(outputStream, this.data);
    }
```

alongside the JSON method we already have:

```java
    public String toJson() throws JsonProcessingException {
        return JSON_MAPPER.writeValueAsString(this.data);
    }
```

I guess the tricky part here would be to make the DLQ work from raw bytes in case something goes wrong which should still be reasonably straightforward though.

**Comment by jordansissel** [comment]
> I guess the tricky part here would be to make the DLQ work from raw bytes

I'm not even sure Manticore exposes a way to write to the request body without creating it fully before the request is sent.

Let's chat this week about some of the tasks here, brainstorm some more, and get a roadmap planned.

**Comment by jordansissel** [comment]
@original-brownbear and I chatted about what task to start on first, and we agreed to do the one-repo-3-plugins task first:

* 1 repo (this repo?) with all 3 inputs (input, filter, output)

Open/unsolved questions:
* What breaks if we have one universal plugin ("integration-elasticsearch") with 3 things (input+filter+output) in it?
* Jarvis may need changes to be able to publish this kind of plugin
* Our [plugin docs tool ](https://github.com/elastic/docs-tools/blob/master/plugindocs.rb) will need to understand how a universal plugin is documented (it assumes docs/index.asciidoc, one plugin per repo, today)
* Make sure bin/logstash-plugin can handle upgrades of universal plugins
* Update any documentation references to 'logstash-output-elasticsearch' (and input/filter) and refer to this new integrated plugin.

**Comment by original-brownbear** [comment]
@jordansissel let's use this repo? We can always rename it if we stop liking the name? :D

**Comment by andrewvc** [comment]
I've updated the top level issue to be a checklist with the added blockers of Jarvis + Docs tooling to support a multi-repo.

**Comment by jordansissel** [comment]
> Patch Jarvis to be able to publish a multi-plugin repo

Instead, do we want to make this new "elasticsearch" plugin a single universal plugin that provides inputs/filters/outputs instead of multiple? Then no major Jarvis changes may be required, I am thinking.

**Comment by andrewvc** [comment]
@jordansissel I'm +1 on that. I've updated the task to just be 'ensure jarvis can publish the plugin'.
